#ddev-generated
ahoyapi: v2
commands:
  readme:
    usage: 'README.md commands'
    imports:
      # addon needs to be installed locally on ddev with 'ddev get .'
      - ./.ddev/readme/.ahoy.readme.yml

  drupal:
    usage: 'Drupal commands'
    imports:
      # addon needs to be installed locally on ddev with 'ddev get .'
      - ./.ddev/brooksdigital/base/.ahoy.brooksdigital-base.drupal.yml

  platform:
    usage: 'Platform commands'
    imports:
      - .ddev/brooksdigital/platformsh/.ahoy.brooksdigital-platformsh.yml
